name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop # Add other branches to trigger the pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: myrepo # Replace with your Docker registry

    steps:
      # Step 1: Check out the repository
      - name: Check out source code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub or your registry
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push all service images
      - name: Build and push service images
        run: |
          # Define services and build/push each one
          SERVICES=(
            "user-service"
            "property-service"
            "search-service"
            "notification-service"
            "action-tracking-service"
            "chat-service"
            "identity-service"
          )

          for SERVICE in "${SERVICES[@]}"
          do
            # Define image name
            IMAGE_NAME=$DOCKER_REGISTRY/$SERVICE:latest

            echo "Building and pushing $IMAGE_NAME..."

            # Build the Docker image
            docker build -t $IMAGE_NAME ./services/$SERVICE

            # Push the Docker image
            docker push $IMAGE_NAME
          done
