name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        run: |
          docker build -t user-service:latest ./services/user-service/UserService
          docker tag user-service:latest myrepo/user-service:latest
          docker push myrepo/user-service:latest
