version: "3.8"

services:
  identity-service:
    build:
      context: ./services/identity-service
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  chat-service:
    build:
      context: ./services/chat-service
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      IdentityService__Authority: "http://identity-service:80"
    depends_on:
      - identity-service

  property-service:
    build:
      context: ./services/property-service
      dockerfile: Dockerfile
    ports:
      - "5004:80"
    environment:
      IdentityService__Authority: "http://identity-service:80"
    depends_on:
      - identity-service

  search-service:
    build:
      context: ./services/search-service
      dockerfile: Dockerfile
    ports:
      - "5005:80"
    environment:
      IdentityService__Authority: "http://identity-service:80"
    depends_on:
      - identity-service

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "5006:80"
    environment:
      IdentityService__Authority: "http://identity-service:80"
    depends_on:
      - identity-service
