version: "3.8"
services:
  user-service:
    build:
      context: ../services/user-service/UserService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  property-service:
    build:
      context: ../services/property-service/PropertyService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
