name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop # Add other branches to trigger the pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: myrepo # Replace with your Docker registry

    steps:
      # Step 1: Check out the repository
      - name: Check out source code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub or your registry
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push service images
      - name: Build and push service images
        run: |
          # Define services and their build contexts
          declare -A SERVICES
          SERVICES=(
            ["identity-service"]="services/identity-service"
            ["chat-service"]="services/chat-service"
            ["property-service"]="services/property-service"
            ["search-service"]="services/search-service"
            ["user-service"]="services/user-service"
            ["notification-service"]="services/notification-service"
            ["action-tracking-service"]="services/action-tracking-service"
          )

          for SERVICE in "${!SERVICES[@]}"
          do
            BUILD_CONTEXT=${SERVICES[$SERVICE]}
            IMAGE_NAME=$DOCKER_REGISTRY/$SERVICE:latest

            echo "Building and pushing $IMAGE_NAME using context $BUILD_CONTEXT..."

            # Build the Docker image
            docker build -t $IMAGE_NAME $BUILD_CONTEXT

            # Push the Docker image
            docker push $IMAGE_NAME
          done
